### ISSUE TITLE
Essentially useless cancel button on edit subjects page

### ISSUE THREAD

**Issue by mirman-wauhls2017** [mirman-school/mirmindr#20]
A cancel button on the edit subject page does absolutely nothing unless you are editing a subject, in which case it stops you from editing the subject. It would be best if the cancel button would only appear when editing the subject.

**Comment by mirman-mtaggart** [comment]
The cancel button clears newSubject back to its default state. So if you're adding a new subject and change your mind, cancel clears the form. Worth keeping.
